### ISSUE TITLE
Implement Cluster Deletion

### ISSUE THREAD

**Issue by chrigl** [kubernetes-sigs/cluster-api-provider-openstack#169] opened 2019-01-04 13:43 UTC
Even though we might move the code to an infrastructure provider at some point (see https://github.com/kubernetes-sigs/cluster-api/issues/639), we need to implement the `Delete` function of the cluster actuator.

This is responsible for cleaning up every external OpenStack Objects created by the Reconcile function.

**Comment by flaper87** [comment] 2019-01-08 11:23
Duplicate of #154 

/close

**Closed by flaper87** 2019-01-08 11:23 UTC
