### ISSUE TITLE
OpenStack 'port' does not get deleted if VM failed to create

### ISSUE THREAD

**Issue by rustycl0ck** [kubernetes-sigs/cluster-api-provider-openstack#723] opened 2021-01-06 04:48 UTC
/kind bug

**What steps did you take and what happened:**
* I created a cluster but had forgotten to create the openstack `keypair` beforehand.
* This led to VM not being created with error: `Invalid key_name provided` from openstack.
* Thus, deleted the cluster with `kubectl delete cluster <my-cluster>`.
* This resulted in errors in the controller-manager pod, complaining that the security group could not be deleted because it is in use.
* The reason for `security group in use` was that the `port` had been created for the VM. But since the VM was never created, the `port` was never attached and thus never got deleted.

**What did you expect to happen:**
If VM is not created for any reason (maybe invalid image name provided, invalid flavor provided, invalid keypair name provided etc.) then the openstack `port` which was created for VM but was never used, should be deleted when trying to delete the cluster.

**Anything else you would like to add:**
Ref: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/controllers/openstackmachine_controller.go#L221-L226
There should be a check here for existing ports too at the time of VM deletion. Maybe a `InstancePortExists`, just like the `InstanceExists` function?

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by jichenjc** [comment] 2021-01-06 07:57
yes, this is valid bug and should be addressed, do you intend to fix this ?
basically, anything created on the fly should be removed if the operation is failed as you pointed out
the VM is not created and the resource which is created for the VM should be removed before the VM is clean up

**Comment by rustycl0ck** [comment] 2021-01-06 08:05
Sure, I can make an attempt to fix this.

**Comment by sbueringer** [comment] 2021-03-26 06:25
@rustycl0ck @jichenjc 

Also got it when implementing e2e tests.
Should be fixed here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798/files#r602041457

**Comment by rustycl0ck** [comment] 2021-03-30 06:06
I think #705 should have probably fixed this issue, I didn't get a chance to try that out though.

**Comment by sbueringer** [comment] 2021-03-30 06:26
Maybe but I got the same error a lot of times when building the e2e test and #705 was already merged.

**Comment by sbueringer** [comment] 2021-03-30 07:07
@rustycl0ck would be nice to get verification if the fix in #705 did actually fix this instance of the problem. In case you're not able to reproduce we could alternatively close the issue and reopen it in case it reoccurs.

**Closed** 2021-03-30 11:03 UTC
Labels: kind/bug
